/* Part of libspu/s_i.c of the SDK reference: functions SpuInit. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "common.h"
#include "libspu_internal.h"

void SpuInit(void) { _SpuInit(0); }
