/* Part of libspu/s_it.c of the SDK reference: functions _spu_getInTransfer. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "common.h"
#include "libspu_internal.h"

void _spu_setInTransfer(s32 arg0);

s32 _spu_getInTransfer(void) { return _spu_inTransfer == 0; }
