/* Part of libspu/spu.c of the SDK reference: functions _spu_reset. Generated by sdkimport.py. */
#define SDK_PART 1
// SPDX-License-Identifier: MIT
#include "common.h"
#include "libspu_internal.h"
#include <psxsdk/kernel.h>
#include <psxsdk/stdarg.h>

#define WASTE_TIME()                                                           \
    sp4 = 0xD;                                                                 \
    for (sp0 = 0; sp0 < 0xF0; sp0++) {                                         \
        sp4 *= 3;                                                              \
    }

static inline void waste_time(volatile s32* p) {
    p[1] = 0xD;
    for (p[0] = 0; p[0] < 0xF0; p[0]++) {
        p[1] *= 3;
    }
}
#define WASTE_TIME_ARR() waste_time(sp)

// _spu_init and _spu_writeByIO share this message. A part cannot own a string
// that a function of another part emits, so a part names it instead and the
// whole file owns it.
#ifdef SDK_PART
extern char _spu_timeout_msg[];
#else
#define _spu_timeout_msg "SPU:T/O [%s]\n"
#endif

s32 _spu_reset(void) {
    volatile s32 sp0;
    volatile s32 sp4;
    u16 cnt;

    cnt = _spu_RXX->rxx.spucnt;
    _spu_RXX->rxx.spucnt = cnt & 0x7FCF;
    WASTE_TIME();
    cnt &= 0xFFCF;
    _spu_RXX->rxx.spucnt = cnt;
    return 0;
}

extern s32 D_800334FC;
extern s32* D_80033514;
extern u16 D_80033540[];
extern s32 _spu_addrMode;
extern s32 _spu_mem_mode;
extern s32 _spu_mem_mode_unit;

s32 _spu_init(s32 arg0);

/* The name _spu_setVoiceRegs is not original. */
void _spu_setVoiceRegs(struct SpuVoiceRegAttr* attr);

s32 _spu_writeByIO(u8* addr, u32 size);

void _spu_FiDMA(void);

extern s32* D_80033508;
extern s32* D_8003350C;
extern s32* D_80033510;
extern s32* D_80033518;
extern s32 D_80033550;
extern s32 D_80033554;
extern s32 D_80033558;

static inline void _spu_FsetDelayW(void) {
    *D_80033518 = (*D_80033518 & 0xF0FFFFFF) | 0x20000000;
}

static inline void _spu_FsetDelayR(void) {
    *D_80033518 = (*D_80033518 & 0xF0FFFFFF) | 0x22000000;
}

void _spu_r_(s32 arg0, u16 arg1, s32 arg2);

#ifndef VERSION_PC
s32 _spu_t(s32 arg0, ...);
#endif

s32 _spu_write(u8* arg0, u32 size);

s32 _spu_read(s32 arg0, u32 size);

void _spu_FsetRXX(s32 arg0, u32 arg1, s32 arg2);

u32 _spu_FsetRXXa(s32 arg0, u32 arg1);

u32 _spu_FgetRXXa(s32 arg0, s32 arg1);
