/* Part of libspu/spu.c of the SDK reference: functions _spu_setVoiceRegs, _spu_writeByIO, _spu_FiDMA, _spu_r_, _spu_t, _spu_write, _spu_read, _spu_FsetRXX, _spu_FsetRXXa, _spu_FgetRXXa. Generated by sdkimport.py. */
#define SDK_PART 1
// SPDX-License-Identifier: MIT
#include "common.h"
#include "libspu_internal.h"
#include <psxsdk/kernel.h>
#include <psxsdk/stdarg.h>

#define WASTE_TIME()                                                           \
    sp4 = 0xD;                                                                 \
    for (sp0 = 0; sp0 < 0xF0; sp0++) {                                         \
        sp4 *= 3;                                                              \
    }

static inline void waste_time(volatile s32* p) {
    p[1] = 0xD;
    for (p[0] = 0; p[0] < 0xF0; p[0]++) {
        p[1] *= 3;
    }
}
#define WASTE_TIME_ARR() waste_time(sp)

// _spu_init and _spu_writeByIO share this message. A part cannot own a string
// that a function of another part emits, so a part names it instead and the
// whole file owns it.
#ifdef SDK_PART
extern char _spu_timeout_msg[];
#else
#define _spu_timeout_msg "SPU:T/O [%s]\n"
#endif

s32 _spu_reset(void);

extern s32 D_800334FC;
extern s32* D_80033514;
extern u16 D_80033540[];
extern s32 _spu_addrMode;
extern s32 _spu_mem_mode;
extern s32 _spu_mem_mode_unit;

s32 _spu_init(s32 arg0);

/* The name _spu_setVoiceRegs is not original. */
void _spu_setVoiceRegs(struct SpuVoiceRegAttr* attr) {
    s32 i;
    u32 mask;
    s32 bSetAll;
    u32 unit;
    u32 addr;
    union SpuUnion* regs;
    s32 pos;
    u32 val;

    mask = attr->mask;
    unit = _spu_mem_mode_unit;
    regs = _spu_RXX;
    bSetAll = mask == 0;
    for (i = 0; i < NUM_SPU_CHANNELS; i++) {
        if (attr->voice & (1 << i)) {
            pos = i * 8;
            if (bSetAll || mask & 1) {
                regs->raw[pos] = attr->volume.left;
            }
            if (bSetAll || mask & 2) {
                regs->raw[pos + 1] = attr->volume.right;
            }
            if (bSetAll || mask & 4) {
                regs->raw[pos + 2] = attr->pitch;
            }
            if (bSetAll || mask & 8) {
                if (_spu_addrMode == 0) {
                    regs->raw[pos + 3] = *(u16*)&attr->addr;
                } else {
                    addr = attr->addr;
                    if (_spu_mem_mode != 0) {
                        if (addr % unit != 0) {
                            addr += unit;
                        }
                    }
                    val = addr >> _spu_mem_mode_plus;
                    regs->raw[pos + 3] = val;
                }
            }
            if (bSetAll || mask & 0x10) {
                regs->raw[pos + 4] = ((u16*)&attr->adsr)[1];
            }
            if (bSetAll || mask & 0x10) {
                regs->raw[pos + 5] = ((u16*)&attr->adsr)[0];
            }
            if (bSetAll || mask & 0x100) {
                regs->raw[pos + 7] = attr->loop_addr;
            }
        }
    }
}

s32 _spu_writeByIO(u8* addr, u32 size) {
    volatile s32 sp0;
    volatile s32 sp4;
    u16 spustat;
    s32 num_to_trans;
    u16* cur_pos;
    s32 spustat_cur;
    s32 i;
    u16 cnt;

    cur_pos = addr;
#ifdef VERSION_PC
    spustat = read_16(0x1F801DAE, __FILE__, __LINE__) & 0x7FF;
    write_16(0x1F801DA6, _spu_tsa, __FILE__, __LINE__);
#else
    spustat = _spu_RXX->rxx.spustat & 0x7FF;
    _spu_RXX->rxx.trans_addr = _spu_tsa;
#endif
    WASTE_TIME();
    while (size != 0) {
        num_to_trans = (size > 0x40) ? 0x40 : size;
        for (i = 0; i < num_to_trans; i += 2) {
#ifndef VERSION_PC
            _spu_RXX->rxx.trans_fifo = *cur_pos++;
#else
            write_16(0x1F801DA8, *cur_pos++, __FILE__, __LINE__);
#endif
        }
#ifndef VERSION_PC
        cnt = _spu_RXX->rxx.spucnt;
        cnt &= ~0x30;
        cnt |= 0x10;
        _spu_RXX->rxx.spucnt = cnt;
#else
        cnt = read_16(0x1F801DAA, __FILE__, __LINE__);
        cnt &= ~0x30;
        cnt |= 0x10;
        write_16(0x1F801DAA, cnt, __FILE__, __LINE__);
#endif
        WASTE_TIME();
        D_800334FC = 0;
#ifndef VERSION_PC
        while (_spu_RXX->rxx.spustat & 0x400) {
#else
        while (read_16(0x1ae, __FILE__, __LINE__) & 0x400) {
#endif
            D_800334FC++;
            if (D_800334FC > 5000) {
                printf(_spu_timeout_msg, "wait (wrdy H -> L)");
                break;
            }
        }
        WASTE_TIME();
        WASTE_TIME();
        size -= num_to_trans;
    }
#ifndef VERSION_PC
    cnt = _spu_RXX->rxx.spucnt;
    cnt &= ~0x30;
    _spu_RXX->rxx.spucnt = cnt;
    D_800334FC = 0;
    spustat_cur = _spu_RXX->rxx.spustat & 0x7FF;
#else
    cnt = read_16(0x1F801DAA, __FILE__, __LINE__);
    cnt &= ~0x30;
    write_16(0x1F801DAA, cnt, __FILE__, __LINE__);
    D_800334FC = 0;
    spustat_cur = read_16(0x1ae, __FILE__, __LINE__) & 0x7FF;
#endif
// ignore this busy loop for now
#ifndef VERSION_PC
    while (spustat_cur != spustat) {
        D_800334FC++;
        if (D_800334FC > 5000) {
            printf(_spu_timeout_msg, "wait (dmaf clear/W)");
            return;
        }
        spustat_cur = _spu_RXX->rxx.spustat & 0x7FF;
    }
#endif
    return spustat_cur;
}

void _spu_FiDMA(void) {
    volatile s32 sp0;
    volatile s32 sp4;
    s32 i;

    if (D_80033550 == 0) {
        WASTE_TIME();
        WASTE_TIME();
        WASTE_TIME();
    }

    _spu_RXX->rxx.spucnt &= 0xFFCF;

    i = 0;
    while (_spu_RXX->rxx.spucnt & 0x30) {
        if (++i > 0xF00) {
            break;
        }
    }

    if (_spu_transferCallback) {
        _spu_transferCallback();
        return;
    }
    DeliverEvent(HwSPU, EvSpCOMP);
}

extern s32* D_80033508;
extern s32* D_8003350C;
extern s32* D_80033510;
extern s32* D_80033518;
extern s32 D_80033550;
extern s32 D_80033554;
extern s32 D_80033558;

static inline void _spu_FsetDelayW(void) {
    *D_80033518 = (*D_80033518 & 0xF0FFFFFF) | 0x20000000;
}

static inline void _spu_FsetDelayR(void) {
    *D_80033518 = (*D_80033518 & 0xF0FFFFFF) | 0x22000000;
}

void _spu_r_(s32 arg0, u16 arg1, s32 arg2) {
    volatile s32 sp0;
    volatile s32 sp4;

    _spu_RXX->rxx.trans_addr = arg1;

    WASTE_TIME();
    WASTE_TIME();

    _spu_RXX->rxx.spucnt |= 0x30;

    WASTE_TIME();
    WASTE_TIME();

    _spu_FsetDelayR();
    *D_80033508 = arg0;
    *D_8003350C = (arg2 << 0x10) | 0x10;
    D_80033550 = 1;
    *D_80033510 = 0x01000200;
}

#ifndef VERSION_PC
s32 _spu_t(s32 arg0, ...) {
    s32 var_a2;
    s32 i;
    u32 addr;
    va_list args;
    u32 count;
    u16 ck2;
    u16 cnt;

    va_start(args, arg0);

    switch (arg0) {
    case 2:
        count = va_arg(args, u32);
        _spu_tsa = count >> _spu_mem_mode_plus;
        _spu_RXX->rxx.trans_addr = _spu_tsa;
        break;

    case 1:
        D_80033550 = 0;
        i = 0;
        while (_spu_RXX->rxx.trans_addr != _spu_tsa) {
            if (++i > 0xF00) {
                return -2;
            }
        }

        cnt = _spu_RXX->rxx.spucnt;
        cnt &= ~0x30;
        cnt |= 0x20;
        _spu_RXX->rxx.spucnt = cnt;
        break;

    case 0:
        D_80033550 = 1;

        i = 0;
        while (_spu_RXX->rxx.trans_addr != _spu_tsa) {
            if (++i > 0xF00) {
                return -2;
            }
        }

        cnt = _spu_RXX->rxx.spucnt;
        cnt &= ~0x30;
        cnt |= 0x30;
        _spu_RXX->rxx.spucnt = cnt;
        break;

    case 3:
        if (D_80033550 == 1) {
            ck2 = 0x30;
        } else {
            ck2 = 0x20;
        }

        i = 0;
        while ((_spu_RXX->rxx.spucnt & 0x30) != ck2) {
            if (++i > 0xF00) {
                return -2;
            }
        }

        if (D_80033550 == 1) {
            _spu_FsetDelayR();
        } else {
            _spu_FsetDelayW();
        }

        count = va_arg(args, u32);
        D_80033554 = count;
        count = va_arg(args, u32);
        D_80033558 = (count / 64);
        D_80033558 += ((count % 64) ? 1 : 0);
        *D_80033508 = D_80033554;
        *D_8003350C = (D_80033558 << 0x10) | 0x10;
        if (D_80033550 == 1) {
            var_a2 = 0x01000200;
        } else {
            var_a2 = 0x01000201;
        }
        *D_80033510 = var_a2;
        break;
    }
    return 0;
}
#endif

s32 _spu_write(u8* arg0, u32 size) {

    if (_spu_transMode != 0) {
        _spu_writeByIO(arg0, size);
        return size;
    }
    _spu_t(2, _spu_tsa << _spu_mem_mode_plus);
    _spu_t(1);
    _spu_t(3, arg0, size);
    return size;
}

s32 _spu_read(s32 arg0, u32 size) {
    _spu_t(2, _spu_tsa << _spu_mem_mode_plus);
    _spu_t(0);
    _spu_t(3, arg0, size);
    return size;
}

void _spu_FsetRXX(s32 arg0, u32 arg1, s32 arg2) {
    if (arg2 == 0) {
#ifdef VERSION_PC
        write_16(0x1F801C00 + arg0 * 2, arg1, __FILE__, __LINE__);
#else
        _spu_RXX->raw[arg0] = arg1;
#endif
        return;
    }

    _spu_RXX->raw[arg0] = arg1 >> _spu_mem_mode_plus;
}

u32 _spu_FsetRXXa(s32 arg0, u32 arg1) {
    u32 temp_a3;
    u32 var_a1;

    var_a1 = arg1;
    if ((_spu_mem_mode != 0) && ((var_a1 % _spu_mem_mode_unit) != 0)) {
        var_a1 += _spu_mem_mode_unit;
        var_a1 &= ~_spu_mem_mode_unitM;
    }
    temp_a3 = var_a1 >> _spu_mem_mode_plus;

    switch (arg0) {
    case -1:
        return temp_a3 & 0xFFFF;
    case -2:
        return var_a1;
    default:
        _spu_RXX->raw[arg0] = temp_a3;
        return var_a1;
    }
}

u32 _spu_FgetRXXa(s32 arg0, s32 arg1) {
    u16 temp = _spu_RXX->raw[arg0];
    if (arg1 == -1) {
        return temp;
    } else {
        return temp << _spu_mem_mode_plus;
    }
}
