/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/a63.c of the SDK reference: BIOS_B_FUNCTION(puts, 0x3F); */
.set noreorder
.set noat
.text
.globl puts
.type puts, @function
puts:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x3F
    nop
.size puts, . - puts
