/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c19.c of the SDK reference: BIOS_A_FUNCTION(setjmp, 0x13); */
.set noreorder
.set noat
.text
.globl setjmp
.type setjmp, @function
setjmp:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x13
    nop
.size setjmp, . - setjmp
