/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c21.c of the SDK reference: BIOS_A_FUNCTION(strcat, 0x15); */
.set noreorder
.set noat
.text
.globl strcat
.type strcat, @function
strcat:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x15
    nop
.size strcat, . - strcat
