/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c23.c of the SDK reference: BIOS_A_FUNCTION(strcmp, 0x17); */
.set noreorder
.set noat
.text
.globl strcmp
.type strcmp, @function
strcmp:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x17
    nop
.size strcmp, . - strcmp
