/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c25.c of the SDK reference: BIOS_A_FUNCTION(strcpy, 0x19); */
.set noreorder
.set noat
.text
.globl strcpy
.type strcpy, @function
strcpy:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x19
    nop
.size strcpy, . - strcpy
