/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c42.c of the SDK reference: BIOS_A_FUNCTION(memcpy, 0x2A); */
.set noreorder
.set noat
.text
.globl memcpy
.type memcpy, @function
memcpy:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x2A
    nop
.size memcpy, . - memcpy
