/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c43.c of the SDK reference: BIOS_A_FUNCTION(memset, 0x2B); */
.set noreorder
.set noat
.text
.globl memset
.type memset, @function
memset:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x2B
    nop
.size memset, . - memset
