/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c47.c of the SDK reference: BIOS_A_FUNCTION(rand, 0x2F); */
.set noreorder
.set noat
.text
.globl rand
.type rand, @function
rand:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x2F
    nop
.size rand, . - rand
