/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libc/c63.c of the SDK reference: BIOS_A_FUNCTION(printf, 0x3F); */
.set noreorder
.set noat
.text
.globl printf
.type printf, @function
printf:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x3F
    nop
.size printf, . - printf
