/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libcard/a74.c of the SDK reference: BIOS_B_FUNCTION(InitCARD, 0x4A); */
.set noreorder
.set noat
.text
.globl InitCARD
.type InitCARD, @function
InitCARD:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x4A
    nop
.size InitCARD, . - InitCARD
