/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libcard/a75.c of the SDK reference: BIOS_B_FUNCTION(StartCARD, 0x4B); */
.set noreorder
.set noat
.text
.globl StartCARD
.type StartCARD, @function
StartCARD:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x4B
    nop
.size StartCARD, . - StartCARD
