/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libcard/a78.c of the SDK reference: BIOS_B_FUNCTION(_card_write, 0x4E); */
.set noreorder
.set noat
.text
.globl _card_write
.type _card_write, @function
_card_write:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x4E
    nop
.size _card_write, . - _card_write
