/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libcard/a80.c of the SDK reference: BIOS_B_FUNCTION(_new_card, 0x50); */
.set noreorder
.set noat
.text
.globl _new_card
.type _new_card, @function
_new_card:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x50
    nop
.size _new_card, . - _new_card
