/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libcard/c171.c of the SDK reference: BIOS_A_FUNCTION(_card_info, 0xAB); */
.set noreorder
.set noat
.text
.globl _card_info
.type _card_info, @function
_card_info:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0xAB
    nop
.size _card_info, . - _card_info
