/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libcard/c172.c of the SDK reference: BIOS_A_FUNCTION(_card_load, 0xAC); */
.set noreorder
.set noat
.text
.globl _card_load
.type _card_load, @function
_card_load:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0xAC
    nop
.size _card_load, . - _card_load
