#!/usr/bin/env python3
"""Controls for structgen.py, on synthetic field files only.

Each case runs the command line in a temporary directory and checks the exit
status, the message and, for merge conflicts, that no output file was written.
The `check` cases need a clang; pass `--cpp` or have one on the usual path.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

TOOL = Path(__file__).resolve().parent / "structgen.py"
DEFAULT_CPP = "/opt/homebrew/opt/llvm/bin/clang"

VALID = """\
# synthetic
type OpaqueFn size=4 align=4   # defined elsewhere
struct Box6 size=6
0x00 s16 origin
0x04 u8  extent
struct Thing size=0x40
0x20 Thing*    next
0x01 u8        flag
0x12 s16       pos
0x24 Box6*     boxes
0x28 Box6      inline_box
0x30 u8        block[8]
0x38 OpaqueFn  fn
0x3c u32       word
"""

CPP = DEFAULT_CPP


def run(*args) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, str(TOOL), *map(str, args)], capture_output=True, text=True)


def out(proc) -> str:
    return proc.stdout + proc.stderr


class Case:
    def __init__(self, name, func):
        self.name, self.func = name, func


def write(directory: Path, name: str, text: str) -> Path:
    path = directory / name
    path.write_text(text)
    return path


def expect_error(directory: Path, text: str, message: str):
    fields = write(directory, "bad.fields", text)
    proc = run("generate", fields, "-o", directory / "bad.h")
    if proc.returncode == 0:
        return "expected failure but exit was 0"
    if message not in out(proc):
        return f"wanted {message!r} in:\n{out(proc)}"
    if "bad.fields:" not in out(proc):
        return f"error carries no line number:\n{out(proc)}"
    if (directory / "bad.h").exists():
        return "header written despite the error"
    return None


def case_valid(d: Path):
    fields = write(d, "a.fields", VALID)
    proc = run("generate", fields, "-o", d / "a.h")
    if proc.returncode != 0:
        return out(proc)
    text = (d / "a.h").read_text()
    for needle in (
        "Generated by ps1/tools/structgen.py",
        "Do not edit",
        "#ifndef A_H",
        "typedef unsigned char u8;",
        "typedef struct Thing {",
        "    struct Thing *next;",
        "    struct Box6 *boxes;",
        "    Box6 inline_box;",
        "    OpaqueFn fn;",
        "    u8 unknown_00;",
        "    u8 unknown_02[16];",
        "    u8 block[8];",
        "} Thing;",
    ):
        if needle not in text:
            return f"header lacks {needle!r}:\n{text}"
    if text.index("typedef struct Box6") > text.index("typedef struct Thing"):
        return "structs are not in file order"
    proc = run("check", fields, "--cpp", CPP)
    if proc.returncode != 0:
        return f"check failed:\n{out(proc)}"
    return None


def case_check_catches_wrong_layout(d: Path):
    """The check must see a header that disagrees with the table."""
    sys.path.insert(0, str(TOOL.parent))
    import structgen

    model = structgen.parse(VALID, "a.fields")
    header = structgen.generate_header(model).replace("s16 pos;", "u8 pos;")
    (d / "types.gen.h").write_text(header)
    try:
        structgen.check_layout(model, CPP, "types.gen.h", d)
    except structgen.FieldsError as exc:
        return None if "layout check failed" in str(exc) else f"wrong error: {exc}"
    return "a mismatching header passed the check"


def case_deterministic(d: Path):
    fields = write(d, "a.fields", VALID)
    for sub in ("one", "two", "x", "y"):
        (d / sub).mkdir()
    run("generate", fields, "-o", d / "one" / "types.gen.h")
    run("generate", fields, "-o", d / "two" / "types.gen.h")
    if (d / "one/types.gen.h").read_bytes() != (d / "two/types.gen.h").read_bytes() or not (d / "one/types.gen.h").stat().st_size:
        return "generation differs between runs"
    a = write(d, "x.fields", "struct S size=8\n0 u32 a\n4 u32 b\n")
    b = write(d, "y.fields", "struct S size=8\n4 u32 b\n0 u32 a\n")
    run("generate", a, "-o", d / "x" / "types.gen.h")
    run("generate", b, "-o", d / "y" / "types.gen.h")
    if (d / "x/types.gen.h").read_text() != (d / "y/types.gen.h").read_text():
        return "field order in the file changes the output"
    run("merge", a, b, "-o", d / "m1.fields")
    run("merge", a, b, "-o", d / "m2.fields")
    if (d / "m1.fields").read_bytes() != (d / "m2.fields").read_bytes():
        return "merge differs between runs"
    return None


def make_error_case(name, text, message):
    return Case(name, lambda d: expect_error(d, text, message))


ERROR_CASES = [
    make_error_case("error-overlap", "struct S size=8\n0 u32 a\n2 u8 b\n", "overlaps"),
    make_error_case("error-overlap-contained", "struct S size=16\n0 u8 a[12]\n4 u8 b\n8 u8 c\n", "overlaps"),
    make_error_case("error-misaligned", "struct S size=8\n1 u32 a\n", "not a multiple of its alignment"),
    make_error_case("error-misaligned-array", "struct S size=8\n2 u32 a[1]\n", "not a multiple of its alignment"),
    make_error_case("error-past-size", "struct S size=8\n0 u32 a\n4 u32 b[2]\n", "ends past the declared size"),
    make_error_case("error-size-not-aligned", "struct S size=6\n0 u32 a\n", "not a multiple of its alignment"),
    make_error_case("error-duplicate-field", "struct S size=8\n0 u8 a\n4 u8 a\n", "duplicate field name"),
    make_error_case("error-duplicate-struct", "struct S size=4\nstruct S size=4\n", "duplicate struct name"),
    make_error_case("error-duplicate-type", "type T size=4 align=4\ntype T size=4 align=4\n", "duplicate type name"),
    make_error_case("error-struct-and-type-name", "type T size=4 align=4\nstruct T size=4\n", "duplicate struct name"),
    make_error_case("error-unknown-type", "struct S size=8\n0 Missing a\n", "unknown type"),
    make_error_case("error-unknown-pointer-type", "struct S size=8\n0 Missing* a\n", "unknown type"),
    make_error_case(
        "error-by-value-before-declared",
        "struct A size=4\n0 B b\nstruct B size=4\n0 u32 x\n",
        "used by value before it is declared",
    ),
    make_error_case("error-by-value-self", "struct A size=4\n0 A a\n", "used by value before it is declared"),
    make_error_case("error-malformed-field", "struct S size=8\n0 u32\n", "malformed line"),
    make_error_case("error-malformed-struct", "struct S 8\n", "malformed line"),
    make_error_case("error-malformed-offset", "struct S size=8\nzero u32 a\n", "malformed line"),
    make_error_case("error-field-outside-struct", "0 u32 a\n", "field outside a struct"),
]


def case_errors_reported_together(d: Path):
    text = "struct S size=8\n0 u32 a\n2 u8 b\n0 Missing c\n7 u16 e\n"
    fields = write(d, "bad.fields", text)
    proc = run("generate", fields, "-o", d / "bad.h")
    errors = [line for line in out(proc).splitlines() if line.startswith("error:")]
    if proc.returncode == 0 or len(errors) < 3:
        return f"expected several errors, got:\n{out(proc)}"
    return None


A = "type Fn size=4 align=4\nstruct Box size=8\n0 u32 a\nstruct Obj size=0x10\n0 u8 x\n8 Box* p\n"
B = "struct Box size=8\n0 u32 a\n4 u16 b\nstruct Obj size=0x10\n0 u8 x\n0xc u8 y\nstruct Extra size=4\n0 u32 e\n"


def case_merge_union(d: Path):
    a, b = write(d, "a.fields", A), write(d, "b.fields", B)
    proc = run("merge", a, b, "-o", d / "m.fields")
    if proc.returncode != 0:
        return out(proc)
    text = (d / "m.fields").read_text()
    expected = (
        "type Fn size=0x4 align=4\n\n"
        "struct Box size=0x8\n0x000 u32 a\n0x004 u16 b\n\n"
        "struct Obj size=0x10\n0x000 u8 x\n0x008 Box* p\n0x00c u8 y\n\n"
        "struct Extra size=0x4\n0x000 u32 e\n"
    )
    if text != expected:
        return f"unexpected merge output:\n{text}"
    # The merged file is itself valid input and merging it again changes nothing.
    again = run("merge", d / "m.fields", a, "-o", d / "m2.fields")
    if again.returncode != 0 or (d / "m2.fields").read_text() != text:
        return f"merge is not idempotent:\n{out(again)}"
    return None


def case_merge_order_by_dependency(d: Path):
    a = write(d, "a.fields", "struct Outer size=16\n8 u32 z\n")
    b = write(d, "b.fields", "struct Inner size=8\n0 u32 x\nstruct Outer size=16\n0 Inner i\n")
    proc = run("merge", a, b, "-o", d / "m.fields")
    if proc.returncode != 0:
        return out(proc)
    text = (d / "m.fields").read_text()
    if text.index("struct Inner") > text.index("struct Outer"):
        return f"embedded struct does not precede its user:\n{text}"
    return None


def merge_conflict(d: Path, a_text: str, b_text: str, message: str):
    a, b = write(d, "a.fields", a_text), write(d, "b.fields", b_text)
    proc = run("merge", a, b, "-o", d / "m.fields")
    if proc.returncode == 0:
        return "expected a conflict but exit was 0"
    text = out(proc)
    if message not in text or "a.fields:" not in text or "b.fields:" not in text:
        return f"wanted {message!r} naming both sources in:\n{text}"
    if (d / "m.fields").exists():
        return "output written despite the conflict"
    return None


MERGE_CONFLICTS = [
    Case(
        "merge-conflict-name",
        lambda d: merge_conflict(d, "struct S size=8\n0 u32 a\n", "struct S size=8\n0 u32 other\n", "offset 0x0"),
    ),
    Case(
        "merge-conflict-type",
        lambda d: merge_conflict(d, "struct S size=8\n0 u32 a\n", "struct S size=8\n0 s32 a\n", "offset 0x0"),
    ),
    Case(
        "merge-conflict-array-length",
        lambda d: merge_conflict(d, "struct S size=8\n0 u8 a[4]\n", "struct S size=8\n0 u8 a[2]\n", "offset 0x0"),
    ),
    Case(
        "merge-conflict-struct-size",
        lambda d: merge_conflict(d, "struct S size=8\n0 u32 a\n", "struct S size=0xc\n0 u32 a\n", "size 0x8"),
    ),
    Case(
        "merge-conflict-name-offset",
        lambda d: merge_conflict(d, "struct S size=8\n0 u32 a\n", "struct S size=8\n4 u32 a\n", "field 'a'"),
    ),
    Case(
        "merge-conflict-type-decl",
        lambda d: merge_conflict(d, "type T size=4 align=4\n", "type T size=8 align=4\n", "type 'T'"),
    ),
    Case(
        "merge-overlap-across-files",
        lambda d: merge_conflict(d, "struct S size=8\n0 u32 a\n", "struct S size=8\n2 u16 b\n", "overlaps"),
    ),
    Case(
        "merge-conflict-type-vs-struct-name",
        lambda d: merge_conflict(d, "type Shared size=4 align=4\n", "struct Shared size=4\n0 u32 a\n", "'Shared' is a type"),
    ),
    Case(
        "merge-conflict-struct-vs-type-name",
        lambda d: merge_conflict(d, "struct Shared size=4\n0 u32 a\n", "type Shared size=4 align=4\n", "'Shared' is a struct"),
    ),
    Case(
        "merge-conflicts-listed-together",
        lambda d: _count_conflicts(d),
    ),
]


def _count_conflicts(d: Path):
    a = write(d, "a.fields", "struct S size=8\n0 u32 a\nstruct T size=4\n0 u32 x\n")
    b = write(d, "b.fields", "struct S size=8\n0 u32 q\nstruct T size=8\n0 u32 x\n")
    proc = run("merge", a, b, "-o", d / "m.fields")
    lines = [line for line in out(proc).splitlines() if "conflict:" in line]
    return None if proc.returncode != 0 and len(lines) == 2 else f"expected two conflicts:\n{out(proc)}"


def case_merge_validates_own_result(d: Path):
    """If the merged model could not be parsed back, merge must fail instead of returning it."""
    sys.path.insert(0, str(TOOL.parent))
    import structgen

    models = [structgen.parse("struct S size=4\n0 u32 a\n", "a")]
    original = structgen.format_fields
    structgen.format_fields = lambda model: original(model) + "struct S size=4\n"
    try:
        structgen.merge_models(models)
    except structgen.FieldsError as exc:
        return None if "merged result is not valid" in str(exc) else f"wrong error: {exc}"
    finally:
        structgen.format_fields = original
    return "an unparseable merge result was returned"


CASES = (
    [Case("valid-generates-and-checks", case_valid), Case("check-catches-wrong-layout", case_check_catches_wrong_layout)]
    + [Case("deterministic", case_deterministic)]
    + ERROR_CASES
    + [Case("errors-reported-together", case_errors_reported_together)]
    + [Case("merge-union", case_merge_union), Case("merge-orders-by-dependency", case_merge_order_by_dependency)]
    + MERGE_CONFLICTS
    + [Case("merge-validates-its-own-result", case_merge_validates_own_result)]
)


def main() -> int:
    global CPP
    parser = argparse.ArgumentParser(description="Controls for structgen.py")
    parser.add_argument("--cpp", default=DEFAULT_CPP if Path(DEFAULT_CPP).exists() else shutil.which("clang"))
    args = parser.parse_args()
    if not args.cpp:
        print("no clang found; pass --cpp", file=sys.stderr)
        return 2
    CPP = args.cpp
    failed = 0
    for case in CASES:
        with tempfile.TemporaryDirectory(prefix="structgen-test-") as tmp:
            problem = case.func(Path(tmp))
        print(f"{'ok  ' if problem is None else 'FAIL'} {case.name}" + ("" if problem is None else f": {problem}"))
        failed += problem is not None
    print(f"{failed} case(s) behaved wrongly" if failed else "all cases behaved as required")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
