/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a07.c of the SDK reference: BIOS_B_FUNCTION(DeliverEvent, 0x7); */
.set noreorder
.set noat
.text
.globl DeliverEvent
.type DeliverEvent, @function
DeliverEvent:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x7
    nop
.size DeliverEvent, . - DeliverEvent
