/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a08.c of the SDK reference: BIOS_B_FUNCTION(OpenEvent, 0x8); */
.set noreorder
.set noat
.text
.globl OpenEvent
.type OpenEvent, @function
OpenEvent:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x8
    nop
.size OpenEvent, . - OpenEvent
