/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a09.c of the SDK reference: BIOS_B_FUNCTION(CloseEvent, 0x9); */
.set noreorder
.set noat
.text
.globl CloseEvent
.type CloseEvent, @function
CloseEvent:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x9
    nop
.size CloseEvent, . - CloseEvent
