/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a10.c of the SDK reference: BIOS_B_FUNCTION(WaitEvent, 0xA); */
.set noreorder
.set noat
.text
.globl WaitEvent
.type WaitEvent, @function
WaitEvent:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0xA
    nop
.size WaitEvent, . - WaitEvent
