/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a11.c of the SDK reference: BIOS_B_FUNCTION(TestEvent, 0xB); */
.set noreorder
.set noat
.text
.globl TestEvent
.type TestEvent, @function
TestEvent:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0xB
    nop
.size TestEvent, . - TestEvent
