/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a12.c of the SDK reference: BIOS_B_FUNCTION(EnableEvent, 0xC); */
.set noreorder
.set noat
.text
.globl EnableEvent
.type EnableEvent, @function
EnableEvent:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0xC
    nop
.size EnableEvent, . - EnableEvent
