/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a13.c of the SDK reference: BIOS_B_FUNCTION(DisableEvent, 0xD); */
.set noreorder
.set noat
.text
.globl DisableEvent
.type DisableEvent, @function
DisableEvent:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0xD
    nop
.size DisableEvent, . - DisableEvent
