/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a23.c of the SDK reference: BIOS_B_FUNCTION(ReturnFromException, 0x17); */
.set noreorder
.set noat
.text
.globl ReturnFromException
.type ReturnFromException, @function
ReturnFromException:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x17
    nop
.size ReturnFromException, . - ReturnFromException
