/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a24.c of the SDK reference: BIOS_B_FUNCTION(ResetEntryInt, 0x18); */
.set noreorder
.set noat
.text
.globl ResetEntryInt
.type ResetEntryInt, @function
ResetEntryInt:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x18
    nop
.size ResetEntryInt, . - ResetEntryInt
