/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a25.c of the SDK reference: BIOS_B_FUNCTION(HookEntryInt, 0x19); */
.set noreorder
.set noat
.text
.globl HookEntryInt
.type HookEntryInt, @function
HookEntryInt:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x19
    nop
.size HookEntryInt, . - HookEntryInt
