/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a36.c of the SDK reference: void EnterCriticalSection() { SYSCALL(1) } */
.set noreorder
.set noat
.text
.globl EnterCriticalSection
.type EnterCriticalSection, @function
EnterCriticalSection:
    addiu $a0, $zero, 1
    syscall
    jr    $ra
    nop
.size EnterCriticalSection, . - EnterCriticalSection
