/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a37.c of the SDK reference: void ExitCriticalSection() { SYSCALL(2) } */
.set noreorder
.set noat
.text
.globl ExitCriticalSection
.type ExitCriticalSection, @function
ExitCriticalSection:
    addiu $a0, $zero, 2
    syscall
    jr    $ra
    nop
.size ExitCriticalSection, . - ExitCriticalSection
