/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a50.c of the SDK reference: BIOS_B_FUNCTION(open, 0x32); */
.set noreorder
.set noat
.text
.globl open
.type open, @function
open:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x32
    nop
.size open, . - open
