/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a52.c of the SDK reference: BIOS_B_FUNCTION(read, 0x34); */
.set noreorder
.set noat
.text
.globl read
.type read, @function
read:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x34
    nop
.size read, . - read
