/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a53.c of the SDK reference: BIOS_B_FUNCTION(write, 0x35); */
.set noreorder
.set noat
.text
.globl write
.type write, @function
write:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x35
    nop
.size write, . - write
