/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a54.c of the SDK reference: BIOS_B_FUNCTION(close, 0x36); */
.set noreorder
.set noat
.text
.globl close
.type close, @function
close:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x36
    nop
.size close, . - close
