/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a65.c of the SDK reference: BIOS_B_FUNCTION(format, 0x41); */
.set noreorder
.set noat
.text
.globl format
.type format, @function
format:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x41
    nop
.size format, . - format
