/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a66.c of the SDK reference: BIOS_B_FUNCTION(firstfile, 0x42); */
.set noreorder
.set noat
.text
.globl firstfile
.type firstfile, @function
firstfile:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x42
    nop
.size firstfile, . - firstfile
