/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a67.c of the SDK reference: BIOS_B_FUNCTION(nextfile, 0x43); */
.set noreorder
.set noat
.text
.globl nextfile
.type nextfile, @function
nextfile:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x43
    nop
.size nextfile, . - nextfile
