/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/a91.c of the SDK reference: BIOS_B_FUNCTION(ChangeClearPAD, 0x5B); */
.set noreorder
.set noat
.text
.globl ChangeClearPAD
.type ChangeClearPAD, @function
ChangeClearPAD:
    addiu $t2, $zero, 0xB0
    jr    $t2
    addiu $t1, $zero, 0x5B
    nop
.size ChangeClearPAD, . - ChangeClearPAD
