/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/c112.c of the SDK reference: BIOS_A_FUNCTION(_bu_init, 0x70); */
.set noreorder
.set noat
.text
.globl _bu_init
.type _bu_init, @function
_bu_init:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x70
    nop
.size _bu_init, . - _bu_init
