/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/c114.c of the SDK reference: BIOS_A_FUNCTION(_96_remove, 0x72); */
.set noreorder
.set noat
.text
.globl _96_remove
.type _96_remove, @function
_96_remove:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x72
    nop
.size _96_remove, . - _96_remove
