/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/c57.c of the SDK reference: BIOS_A_FUNCTION(InitHeap, 0x39); */
.set noreorder
.set noat
.text
.globl InitHeap
.type InitHeap, @function
InitHeap:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x39
    nop
.size InitHeap, . - InitHeap
