/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/c67.c of the SDK reference: BIOS_A_FUNCTION(Exec, 0x43); */
.set noreorder
.set noat
.text
.globl Exec
.type Exec, @function
Exec:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x43
    nop
.size Exec, . - Exec
