/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/c68.c of the SDK reference: BIOS_A_FUNCTION(FlushCache, 0x44); */
.set noreorder
.set noat
.text
.globl FlushCache
.type FlushCache, @function
FlushCache:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x44
    nop
.size FlushCache, . - FlushCache
