/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/c73.c of the SDK reference: BIOS_A_FUNCTION(GPU_cw, 0x49); */
.set noreorder
.set noat
.text
.globl GPU_cw
.type GPU_cw, @function
GPU_cw:
    addiu $t2, $zero, 0xA0
    jr    $t2
    addiu $t1, $zero, 0x49
    nop
.size GPU_cw, . - GPU_cw
