/* SPDX-License-Identifier: MIT */
/* Generated by sdkimport.py from libapi/l10.c of the SDK reference: BIOS_C_FUNCTION(ChangeClearRCnt, 0xA); */
.set noreorder
.set noat
.text
.globl ChangeClearRCnt
.type ChangeClearRCnt, @function
ChangeClearRCnt:
    addiu $t2, $zero, 0xC0
    jr    $t2
    addiu $t1, $zero, 0xA
    nop
.size ChangeClearRCnt, . - ChangeClearRCnt
