/* Part of libcd/sys.c of the SDK reference: functions CdStatus. Generated by sdkimport.py. */
#define SDK_PART 1
// SPDX-License-Identifier: MIT
#include "libcd_internal.h"
#include <common.h>

#include "registers.h"

extern CdlCB CD_cbready;
extern CdlCB CD_cbsync;
extern int CD_status;
extern unsigned char CD_mode;
extern unsigned char CD_com;
extern unsigned char CD_pos[];
extern int D_80032AB0;
extern char* D_80032AC8[];
extern char* D_80032B48[];

extern int CD_wait_shell(void);

#ifdef SDK_PART
extern int D_80032A24[];
#else
static int D_80032A24[] = {0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0};
#endif

inline char CdStatus(void) { return CD_status; }

int CdMode(void);

int CdLastCom(void);

unsigned char* CdLastPos(void);

int CdReset(int mode);

void CdFlush(void);

s32 CdSetDebug(s32 arg0);

char* CdComstr(unsigned char com);

char* CdIntstr(u8 intr);

int CdSync(int mode, u_char* result);

int CdReady(int mode, u_char* result);

CdlCB CdSyncCallback(CdlCB func);

CdlCB CdReadyCallback(CdlCB func);

static inline cd_cw(u8 com, u8* param, u_char* result, s32 arg3) {
    CdlCB old = CD_cbsync;
    int count = 4;

    while (count--) {
        if (com == CdlGetlocL && !(CdStatus() & CdlStatRead)) {
            CD_wait_shell();
            continue;
        }
        if (com != CdlNop) {
            CD_cbsync = NULL;
            CD_wait_shell();
            if (param != NULL && D_80032A24[com] != 0 &&
                CD_cw(CdlSetloc, param, result, 0)) {
                continue;
            }
            CD_cbsync = old;
        }
        if (!CD_cw(com, param, result, arg3)) {
            return 0;
        }
    }

    CD_cbsync = old;
    return -1;
}

int CdControl(u8 com, u8* param, u_char* result);

int CdControlF(u8 com, u8* param);

int CdControlB(u8 com, u8* param, u_char* result);

int CdMix(CdlATV* vol);

int CdGetSector(void* madr, int size);

long CdDataCallback(void (*func)());

void CdDataSync(int mode);

CdlLOC* CdIntToPos(int i, CdlLOC* p);

int CdPosToInt(CdlLOC* p);
