/* Part of libsnd/play.c of the SDK reference: functions _SsSndPlay. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "libsnd_i.h"

void _SsSndPlay(s16 arg0, s16 arg1) { _SsSeqPlay(arg0, arg1); }
