/* Part of libsnd/ssstart.c of the SDK reference: functions _SsSeqCalledTbyT_1per2. Generated by sdkimport.py. */
#define SDK_PART 1
// SPDX-License-Identifier: MIT
#include "common.h"
#include "libsnd_i.h"

/* Adapted: in this SDK version the tick environment is not a struct but
   separate variables (each is addressed with its own lui in the image), and
   _snd_seq_tick_env is not initialised statically. _SsInit sets them. Names
   are not original. libsnd_i.h still declares the unused struct. */
#ifdef SDK_PART
extern s32 _snd_tick_mode;
extern s32 _snd_tick_flag;
extern s32 _snd_tick_vsync;
extern s32 _snd_tick_irq;
extern s32 _snd_tick_half;
extern void (*_snd_tick_prev_cb)(void);
extern s32 _snd_tick_toggle;
#else
s32 _snd_tick_mode;
s32 _snd_tick_flag;
s32 _snd_tick_vsync;
s32 _snd_tick_irq;
s32 _snd_tick_half;
void (*_snd_tick_prev_cb)(void);
static s32 _snd_tick_toggle;
#endif

long StartRCnt(unsigned long);

extern inline void _SsTrapIntrVSync(void) {
    if (_snd_tick_prev_cb != NULL) {
        _snd_tick_prev_cb();
    }
    SsSeqCalledTbyT();
}

void _SsSeqCalledTbyT_1per2(void) {
    if (_snd_tick_toggle == 0) {
        _snd_tick_toggle = 1;
    } else {
        _snd_tick_toggle = 0;
        SsSeqCalledTbyT();
    }
}

void _SsStart(s32 arg0);

void SsStart(void);

void SsStart2(void);
