/* Part of libsnd/ssstart.c of the SDK reference: functions _SsStart. Generated by sdkimport.py. */
#define SDK_PART 1
// SPDX-License-Identifier: MIT
#include "common.h"
#include "libsnd_i.h"

/* Adapted: in this SDK version the tick environment is not a struct but
   separate variables (each is addressed with its own lui in the image), and
   _snd_seq_tick_env is not initialised statically. _SsInit sets them. Names
   are not original. libsnd_i.h still declares the unused struct. */
#ifdef SDK_PART
extern s32 _snd_tick_mode;
extern s32 _snd_tick_flag;
extern s32 _snd_tick_vsync;
extern s32 _snd_tick_irq;
extern s32 _snd_tick_half;
extern void (*_snd_tick_prev_cb)(void);
extern s32 _snd_tick_toggle;
#else
s32 _snd_tick_mode;
s32 _snd_tick_flag;
s32 _snd_tick_vsync;
s32 _snd_tick_irq;
s32 _snd_tick_half;
void (*_snd_tick_prev_cb)(void);
static s32 _snd_tick_toggle;
#endif

long StartRCnt(unsigned long);

extern inline void _SsTrapIntrVSync(void) {
    if (_snd_tick_prev_cb != NULL) {
        _snd_tick_prev_cb();
    }
    SsSeqCalledTbyT();
}

extern inline void _SsSeqCalledTbyT_1per2(void) {
    if (_snd_tick_toggle == 0) {
        _snd_tick_toggle = 1;
    } else {
        _snd_tick_toggle = 0;
        SsSeqCalledTbyT();
    }
}

void _SsStart(s32 arg0) {
    u16 rcnt_target;
    u32 rcnt_spec;

    s32 wait = 1000;
    while (--wait >= 0) {
    }

    switch (_snd_tick_mode) {
    case 0:
        return;

    case 5:
        if (arg0 == 0) {
            _snd_tick_vsync++;
        } else {
            rcnt_spec = 0xF2000003;
            _snd_tick_irq = 0;
            rcnt_target = 1;
        }
        break;

    case 3:
        rcnt_spec = 0xF2000002;
        rcnt_target = 0x89D0;
        _snd_tick_irq = 6;
        break;

    case 2:
        rcnt_spec = 0xF2000002;
        rcnt_target = 0x44E8;
        _snd_tick_irq = 6;
        break;

    default:
        if (_snd_tick_flag != 0) {
            return;
        }
        rcnt_spec = 0xF2000002;
        _snd_tick_irq = 6;
        if (_snd_tick_mode < 0x46) {
            rcnt_target = 0x204CC0 / _snd_tick_mode;
            _snd_tick_half++;
        } else {
            rcnt_target = 0x409980 / _snd_tick_mode;
        }
        break;
    }

    if (_snd_tick_vsync != 0) {
        VSyncCallback(SsSeqCalledTbyT);
    } else {
        EnterCriticalSection();
        ResetRCnt(rcnt_spec);
        SetRCnt(rcnt_spec, rcnt_target, 0x1000);
        wait = 2000;
        while (--wait >= 0) {
        }
        wait = 2000;
        while (--wait >= 0) {
        }
        StartRCnt(rcnt_spec);
        if (_snd_tick_irq == 0) {
            _snd_tick_prev_cb = InterruptCallback(0, NULL);
            InterruptCallback(_snd_tick_irq, _SsTrapIntrVSync);
        } else if (_snd_tick_half == 0) {
            InterruptCallback(_snd_tick_irq, SsSeqCalledTbyT);
        } else {
            InterruptCallback(_snd_tick_irq, _SsSeqCalledTbyT_1per2);
        }
        ExitCriticalSection();
    }
}

void SsStart(void);

void SsStart2(void);
