/* Part of libsnd/ssvol.c of the SDK reference: functions SsSeqSetVol. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "libsnd_i.h"

void _SsSndSetVol(s32 arg0, s32 arg1, u16 arg2, u16 arg3);

void SsSeqSetVol(short arg0, short arg1, short arg2) {
    SpuVmSetSeqVol(arg0, arg1, arg2, 0);
}

void SsSepSetVol(s16 sep_access_num, s16 seq_num, s16 voll, s16 volr);

void SsSeqGetVol(s16 access_num, s16 seq_num, s16* voll, s16* volr);
