/* Part of libsnd/ut_roff.c of the SDK reference: functions SsUtReverbOff. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "libsnd_i.h"

void SsUtReverbOff(void) { SpuSetReverb(0); }
