/* Part of libsnd/ut_ron.c of the SDK reference: functions SsUtReverbOn. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "libsnd_i.h"

void SsUtReverbOn(void) { SpuSetReverb(1); }
