/* Part of libsnd/vm_don.c of the SDK reference: functions SpuVmDamperOn. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "libsnd_i.h"

void SpuVmDamperOn(void) { _svm_damper = 2; }
