/* Part of libsnd/vm_doff.c of the SDK reference: functions SpuVmDamperOff. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "libsnd_i.h"

void SpuVmDamperOff(void) { _svm_damper = 0; }
