/* Part of libsnd/vmanager.c of the SDK reference: functions SsUtKeyOn, SsUtKeyOff, SsUtKeyOnV, SsUtKeyOffV, SsUtPitchBend, SsUtChangePitch, SsUtChangeADSR, SsUtGetDetVVol, SsUtSetDetVVol, SsUtGetVVol, SsUtSetVVol, SsUtAutoVol, SsUtAutoPan, SsUtAllKeyOff. Generated by sdkimport.py. */
#define SDK_PART 1
// SPDX-License-Identifier: MIT
#include "common.h"
#include "libsnd_i.h"

/* SDK_PART: a unit that holds only part of this file does not own the file's data. */
#if defined(VERSION_PC) || defined(SDK_PART)
extern s16 _svm_sreg_buf[];
extern char _svm_sreg_dirty[];
extern struct SpuVoice _svm_voice[];
extern s32 D_8003BD08;
extern s32 _svm_envx_hist[];
extern u32 _ss_spu_vm_rec[];
#else
static s16 _svm_sreg_buf[NUM_SPU_CHANNELS * 8];
static char _svm_sreg_dirty[NUM_SPU_CHANNELS];
static struct SpuVoice _svm_voice[NUM_SPU_CHANNELS];
static s32 D_8003BD08;
static s32 _svm_envx_hist[0x10];
STATIC_PAD_BSS(4);
static u32 _ss_spu_vm_rec[0x20];
#endif

#ifdef SDK_PART
extern u16* D_80032F10;
extern u16 D_80032F14[];
#else
static u16* D_80032F10 = (u16*)0x1F801C00;
static u16 D_80032F14[] = {
    0x1000, 0x100E, 0x101D, 0x102C, 0x103B, 0x104A, 0x1059, 0x1068, 0x1078,
    0x1087, 0x1096, 0x10A5, 0x10B5, 0x10C4, 0x10D4, 0x10E3, 0x10F3, 0x1103,
    0x1113, 0x1122, 0x1132, 0x1142, 0x1152, 0x1162, 0x1172, 0x1182, 0x1193,
    0x11A3, 0x11B3, 0x11C4, 0x11D4, 0x11E5, 0x11F5, 0x1206, 0x1216, 0x1227,
    0x1238, 0x1249, 0x125A, 0x126B, 0x127C, 0x128D, 0x129E, 0x12AF, 0x12C1,
    0x12D2, 0x12E3, 0x12F5, 0x1306, 0x1318, 0x132A, 0x133C, 0x134D, 0x135F,
    0x1371, 0x1383, 0x1395, 0x13A7, 0x13BA, 0x13CC, 0x13DE, 0x13F1, 0x1403,
    0x1416, 0x1428, 0x143B, 0x144E, 0x1460, 0x1473, 0x1486, 0x1499, 0x14AC,
    0x14BF, 0x14D3, 0x14E6, 0x14F9, 0x150D, 0x1520, 0x1534, 0x1547, 0x155B,
    0x156F, 0x1583, 0x1597, 0x15AB, 0x15BF, 0x15D3, 0x15E7, 0x15FB, 0x1610,
    0x1624, 0x1638, 0x164D, 0x1662, 0x1676, 0x168B, 0x16A0, 0x16B5, 0x16CA,
    0x16DF, 0x16F4, 0x170A, 0x171F, 0x1734, 0x174A, 0x175F, 0x1775, 0x178B,
    0x17A1, 0x17B6, 0x17CC, 0x17E2, 0x17F9, 0x180F, 0x1825, 0x183B, 0x1852,
    0x1868, 0x187F, 0x1896, 0x18AC, 0x18C3, 0x18DA, 0x18F1, 0x1908, 0x191F,
    0x1937, 0x194E, 0x1965, 0x197D, 0x1995, 0x19AC, 0x19C4, 0x19DC, 0x19F4,
    0x1A0C, 0x1A24, 0x1A3C, 0x1A55, 0x1A6D, 0x1A85, 0x1A9E, 0x1AB7, 0x1ACF,
    0x1AE8, 0x1B01, 0x1B1A, 0x1B33, 0x1B4C, 0x1B66, 0x1B7F, 0x1B98, 0x1BB2,
    0x1BCC, 0x1BE5, 0x1BFF, 0x1C19, 0x1C33, 0x1C4D, 0x1C67, 0x1C82, 0x1C9C,
    0x1CB7, 0x1CD1, 0x1CEC, 0x1D07, 0x1D22, 0x1D3D, 0x1D58, 0x1D73, 0x1D8E,
    0x1DA9, 0x1DC5, 0x1DE0, 0x1DFC, 0x1E18, 0x1E34, 0x1E50, 0x1E6C, 0x1E88,
    0x1EA4, 0x1EC1, 0x1EDD, 0x1EFA, 0x1F16, 0x1F33, 0x1F50, 0x1F6D, 0x1F8A,
    0x1FA7, 0x1FC5, 0x1FE2, 0x2000};
#endif

extern s16 _svm_vcf;
extern s16 _svm_orev1;
extern s16 _svm_orev2;
extern u8 _svm_auto_kof_mode;

static inline u16 get_field_0x1a() { return _svm_cur.field_0x1a; }

u8 SpuVmAlloc(s32 arg0);

#ifndef VERSION_PC
void SpuVmKeyOnNow(u8 vagCount, u16 arg2);
#endif

void SpuVmDoAllocate(void);

void vmNoiseOn(u8 arg0);

void vmNoiseOn2(u8 voice, u16 arg1, u16 arg2, u16 arg3, u16 arg4);

u16 note2pitch();

s32 note2pitch2(u16 arg0, u16 arg1);

void SePitchBend(u8 voice, s16 arg1);

static inline u8 _SsVmSelectToneAndVag(u8* toneIdx, u8* vagIdx) {
    u8 i;
    u8 vagCount;
    VagAtr* vagAttr;

    vagCount = 0;
    for (i = 0; i < _svm_cur.field_0_sep_sep_no_tonecount; i++) {
        vagAttr = &_svm_tn[(_svm_cur.field_7_fake_program * 0x10) + i];
        if (vagAttr->min > _svm_cur.field_2_note ||
            _svm_cur.field_2_note > vagAttr->max) {
            continue;
        }
        vagIdx[vagCount] = vagAttr->vag;
        toneIdx[vagCount++] = i;
    }
    return vagCount;
}

void SsUtVibrateOn(void);

void SsUtVibrateOff(void);

#define klabs(A) (((A) >= 0) ? (A) : -(A))

void SeAutoVol(s16 voice, s16 start_vol, s16 end_vol, s16 delta_time);

void SetAutoVol(s16 voice);

void SeAutoPan(s16 voice, s16 start_pan, s16 end_pan, s16 delta_time);

void SetAutoPan(s16 voice);

void SpuVmInit(u8 arg0);

void SpuVmNoiseOnWithAdsr(s32 arg0, s32 arg1, s32 arg2, s32 arg3);

void SpuVmNoiseOff(void);

void SpuVmNoiseOn(s32 arg0, s32 arg1);

s16 SpuVmPBVoice(
    s16 voice, s16 seq_sep_no, s16 vabId, s16 program, u16 amount);

s32 SpuVmPitchBend(s16 arg0, s16 arg1, s16 arg2, s16 arg3);

#ifndef VERSION_PC
void SpuVmFlush(void);
#endif

#ifndef VERSION_PC
s32 SpuVmKeyOn(s16 arg0, s16 vabId, s16 prog, u16 note, u16 voll, u16 volr);
#endif

s32 SpuVmKeyOff(s16 arg0, s16 vabId, s16 prog, u16 note);

void SpuVmSeKeyOn(s16 vabId, s16 prog, u16 note, s32 arg3, u16 voll, u16 volr);

void SpuVmSeKeyOff(s16 vabId, s16 prog, u16 note);

void KeyOnCheck(void);

s32 SpuVmSetSeqVol(s16 seq_sep_no, u16 voll, u16 volr, s16 arg3);

s32 SpuVmGetSeqVol(s16 arg0, s16* arg1, s16* arg2);

s16 SpuVmGetSeqLVol(s16 arg0);

s16 SpuVmGetSeqRVol(s16 arg0);

void SpuVmSeqKeyOff(s16 arg0);

s32 SpuVmSetProgVol(s16 vabId, s16 prog, u8 arg2);

s32 SpuVmGetProgVol(s16 vabId, s16 prog);

s32 SpuVmSetProgPan(s16 vabId, s16 prog, u8 pan);

s32 SpuVmGetProgPan(s16 vabId, s16 prog);

#ifndef VERSION_PC
s32 SpuVmSetVol(s16 seq_sep_no, s16 vabId, s16 prog, u16 arg3, u16 arg4);
#endif

s16 SsUtKeyOn(
    s16 vabId, s16 prog, s16 tone, s16 note, s16 fine, s16 voll, s16 volr) {
    s16 voice;
    s32 tone2;

    if (_snd_ev_flag == 1) {
        return -1;
    }
    _snd_ev_flag = 1;

    if (SpuVmVSetUp(vabId, prog)) {
        _snd_ev_flag = 0;
        return -1;
    }
    _svm_cur.field_16_vag_idx = 0x21;
    _svm_cur.field_2_note = note;
    _svm_cur.field_0x3 = fine;
    _svm_cur.field_C_vag_idx = tone;
    if (voll == volr) {
        _svm_cur.field_0x5 = 0x40;
        _svm_cur.field_4_voll = voll;
    } else if (volr < voll) {
        _svm_cur.field_4_voll = voll;
        _svm_cur.field_0x5 = (volr * 0x40) / voll;
    } else {
        _svm_cur.field_4_voll = volr;
        _svm_cur.field_0x5 = 0x7F - ((voll * 0x40) / volr);
    }
    _svm_cur.field_A_mvol = _svm_pg[prog].mvol;
    _svm_cur.field_B_mpan = _svm_pg[prog].mpan;
    _svm_cur.field_0_sep_sep_no_tonecount = _svm_pg[prog].tones;

    tone2 = _svm_cur.field_C_vag_idx + (_svm_cur.field_7_fake_program * 0x10);
    _svm_cur.field_F_prior = _svm_tn[tone2].prior;
    _svm_cur.field_18_voice_idx = _svm_tn[tone2].vag;
    _svm_cur.field_D_vol = _svm_tn[tone2].vol;
    _svm_cur.field_E_pan = _svm_tn[tone2].pan;
    _svm_cur.field_10_centre = _svm_tn[tone2].center;
    _svm_cur.field_11_shift = _svm_tn[tone2].shift;
    _svm_cur.field_14_seq_sep_no = _svm_tn[tone2].mode;
    _svm_cur.field_12_mode = _svm_tn[tone2].min;
    _svm_cur.field_0x13 = _svm_tn[tone2].max;
    if (_svm_cur.field_18_voice_idx == 0) {
        _snd_ev_flag = 0;
        return -1;
    }

    voice = SpuVmAlloc(_svm_cur.field_18_voice_idx);

    if (voice == spuVmMaxVoice) {
        _snd_ev_flag = 0;
        return -1;
    }

    _svm_cur.field_0x1a = voice;
    _svm_voice[voice].unke = 0x21;
    _svm_voice[voice].vabId = vabId;
    _svm_voice[voice].unk10 = _svm_cur.field_7_fake_program;
    _svm_voice[voice].prog = prog;
    _svm_voice[voice].unk0 = _svm_cur.field_18_voice_idx;
    _svm_voice[voice].tone = _svm_cur.field_C_vag_idx;
    _svm_voice[voice].note = note;
    _svm_voice[voice].unk1b = 1;
    _svm_voice[voice].unk2 = 0;

    SpuVmDoAllocate();
    if (_svm_cur.field_18_voice_idx == 0xFF) {
        vmNoiseOn(voice);
    } else {
        SpuVmKeyOnNow(1, note2pitch2(note, fine));
    }
    _snd_ev_flag = 0;
    return voice;
}

short SsUtKeyOff(s16 voice, s16 vabId, s16 prog, s16 tone, s16 note) {
    unsigned char new_var;
    u16 bitsUpper;
    u16 bitsLower;
    u16 temp_v1;

    if (_snd_ev_flag == 1) {
        return -1;
    }
    _snd_ev_flag = 1;

    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        if ((_svm_voice[voice].vabId == vabId) &&
            (_svm_voice[voice].prog == prog) &&
            (_svm_voice[voice].tone == tone) &&
            (_svm_voice[voice].note == note)) {
            if (_svm_voice[voice].unk0 == 0xFF) {
                new_var = voice;
                _svm_voice[new_var].unk1b = 0;
                _svm_voice[new_var].unk04 = 0;
                D_80032F10[202] = 0;
                D_80032F10[203] = 0;
            } else {
                _svm_cur.field_0x1a = voice;
                temp_v1 = get_field_0x1a();
                if (temp_v1 < 0x10) {
                    bitsLower = 1 << temp_v1;
                    bitsUpper = 0;
                } else {
                    bitsLower = 0;
                    bitsUpper = 1 << (temp_v1 - 0x10);
                }
                _svm_voice[temp_v1].unk1b = 0;
                _svm_voice[temp_v1].unk04 = 0;
                _svm_voice[temp_v1].unk0 = 0;
                _svm_okof1 |= bitsLower;
                _svm_okof2 |= bitsUpper;
                _svm_okon1 &= ~_svm_okof1;
                _svm_okon2 &= ~_svm_okof2;
            }
            _snd_ev_flag = 0;
            return 0;
        }
    }
    _snd_ev_flag = 0;
    return -1;
}

s16 SsUtKeyOnV(s16 voice, s16 vabId, s16 prog, s16 tone, s16 note, s16 fine,
               s16 voll, s16 volr) {
    s32 tone2;

    if (_snd_ev_flag == 1) {
        return -1;
    }
    _snd_ev_flag = 1;
    if (voice < 0 || voice >= NUM_SPU_CHANNELS) {
        _snd_ev_flag = 0;
        return -1;
    }
    if (SpuVmVSetUp(vabId, prog)) {
        _snd_ev_flag = 0;
        return -1;
    }
    _svm_cur.field_16_vag_idx = 0x21;
    _svm_cur.field_2_note = note;
    _svm_cur.field_0x3 = fine;
    _svm_cur.field_C_vag_idx = tone;

    if (voll == volr) {
        _svm_cur.field_0x5 = 0x40;
        _svm_cur.field_4_voll = voll;
    } else if (volr < voll) {
        _svm_cur.field_0x5 = (volr * 0x40) / voll;
        _svm_cur.field_4_voll = voll;
    } else {
        _svm_cur.field_0x5 = 0x7F - ((voll * 0x40) / volr);
        _svm_cur.field_4_voll = volr;
    }

    _svm_cur.field_A_mvol = _svm_pg[prog].mvol;
    _svm_cur.field_B_mpan = _svm_pg[prog].mpan;
    _svm_cur.field_0_sep_sep_no_tonecount = _svm_pg[prog].tones;

    tone2 = _svm_cur.field_C_vag_idx + (_svm_cur.field_7_fake_program * 0x10);
    _svm_cur.field_F_prior = _svm_tn[tone2].prior;
    _svm_cur.field_18_voice_idx = _svm_tn[tone2].vag;
    _svm_cur.field_D_vol = _svm_tn[tone2].vol;
    _svm_cur.field_E_pan = _svm_tn[tone2].pan;
    _svm_cur.field_10_centre = _svm_tn[tone2].center;
    _svm_cur.field_11_shift = _svm_tn[tone2].shift;
    _svm_cur.field_14_seq_sep_no = _svm_tn[tone2].mode;
    _svm_cur.field_12_mode = _svm_tn[tone2].min;
    _svm_cur.field_0x13 = _svm_tn[tone2].max;

    if (_svm_cur.field_18_voice_idx == 0) {
        _snd_ev_flag = 0;
        return -1;
    }

    _svm_cur.field_0x1a = voice;
    _svm_voice[voice].unke = 0x21;
    _svm_voice[voice].vabId = vabId;
    _svm_voice[voice].unk10 = _svm_cur.field_7_fake_program;
    _svm_voice[voice].prog = prog;
    _svm_voice[voice].unk0 = _svm_cur.field_18_voice_idx;
    _svm_voice[voice].tone = _svm_cur.field_C_vag_idx;
    _svm_voice[voice].note = note;
    _svm_voice[voice].unk1b = 1;
    _svm_voice[voice].unk2 = 0;
    SpuVmDoAllocate();
    if (_svm_cur.field_18_voice_idx == 0xFF) {
        vmNoiseOn(voice);
    } else {
        SpuVmKeyOnNow(1, note2pitch2(note, fine));
    }
    _snd_ev_flag = 0;
    return voice;
}

s32 SsUtKeyOffV(s16 voice) {
    u16 bitsUpper;
    u16 bitsLower;
    u16 temp2;

    if (_snd_ev_flag == 1) {
        return -1;
    }
    _snd_ev_flag = 1;

    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        _svm_cur.field_0x1a = voice;
        temp2 = get_field_0x1a();
        if (temp2 < 0x10) {
            bitsLower = 1 << temp2;
            bitsUpper = 0;
        } else {
            bitsLower = 0;
            bitsUpper = 1 << (temp2 - 0x10);
        }

        _svm_voice[temp2].unk1b = 0;
        _svm_voice[temp2].unk04 = 0;
        _svm_voice[temp2].unk0 = 0;

        _snd_ev_flag = 0;

        _svm_okof1 |= bitsLower;
        _svm_okof2 |= bitsUpper;

        _svm_okon1 &= ~_svm_okof1;
        _svm_okon2 &= ~_svm_okof2;
        return 0;
    }
    _snd_ev_flag = 0;
    return -1;
}

s16 SsUtPitchBend(s16 voice, s16 vabId, s16 prog, s16 note, s16 pbend) {
    SpuVmVSetUp(vabId, prog);
    _svm_cur.field_16_vag_idx = 0x21;
    return -((SpuVmPBVoice(voice, 0x21, vabId, prog, pbend) << 0x10) == 0);
}

short SsUtChangePitch(short voice, short vabId, short prog, short old_note,
                      short old_fine, short new_note, short new_fine) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        if ((_svm_voice[voice].vabId == vabId) &&
            (_svm_voice[voice].prog == prog) &&
            (_svm_voice[voice].note == old_note)) {
            SpuVmVSetUp(_svm_voice[voice].vabId, _svm_voice[voice].prog);
            _svm_cur.field_16_vag_idx = 0x21;
            _svm_cur.field_0x1a = voice;
            _svm_cur.field_C_vag_idx = _svm_voice[voice].tone;
            _svm_sreg_buf[voice * 8 + 2] = note2pitch2(new_note, new_fine);
            _svm_sreg_dirty[voice] |= 4;
            return 0;
        }
    }
    return -1;
}

s16 SsUtChangeADSR(
    s16 voice, s16 vabId, s16 prog, s16 old_note, u16 adsr1, u16 adsr2) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        if ((_svm_voice[voice].vabId == vabId) &&
            (_svm_voice[voice].prog == prog) &&
            (_svm_voice[voice].note == old_note)) {
            _svm_sreg_buf[voice * 8 + 4] = adsr1;
            _svm_sreg_buf[voice * 8 + 5] = adsr2;
            _svm_sreg_dirty[voice] |= 0x30;
            return 0;
        }
    }
    return -1;
}

s16 SsUtGetDetVVol(s16 voice, s16* voll, s16* volr) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        *voll = D_80032F10[voice * 8 + 0];
        *volr = D_80032F10[voice * 8 + 1];
        return 0;
    }
    return -1;
}

s32 SsUtSetDetVVol(s16 voice, s16 arg1, s16 arg2) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        _svm_sreg_buf[voice * 8 + 0] = arg1;
        _svm_sreg_buf[voice * 8 + 1] = arg2;
        _svm_sreg_dirty[voice] |= 3;
        return 0;
    }

    return -1;
}

s16 SsUtGetVVol(s16 voice, s16* voll, s16* volr) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        s16 temp1 = D_80032F10[voice * 8 + 0];
        s16 temp2 = D_80032F10[voice * 8 + 1];
        *voll = temp1 / 0x81;
        *volr = temp2 / 0x81;
        return 0;
    }
    return -1;
}

s16 SsUtSetVVol(s16 voice, s16 voll, s16 volr) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        voll *= 0x81;
        volr *= 0x81;
        _svm_sreg_buf[voice * 8 + 1] = volr;
        _svm_sreg_buf[voice * 8 + 0] = voll;
        _svm_sreg_dirty[voice] |= 3;
        return 0;
    }

    return -1;
}

s16 SsUtAutoVol(s16 voice, s16 start_vol, s16 end_vol, s16 delta_time) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        SeAutoVol(voice, start_vol, end_vol, delta_time);
        return 0;
    }
    return -1;
}

s16 SsUtAutoPan(s16 voice, s16 start_pan, s16 end_pan, s16 delta_time) {
    if (voice >= 0 && voice < NUM_SPU_CHANNELS) {
        SeAutoPan(voice, start_pan, end_pan, delta_time);
        return 0;
    }
    return -1;
}

void SsUtAllKeyOff(void) {
    s16 voice;
    u16 bitsUpper;
    u16 bitsLower;
    u16 temp2;
    s16 pos;

    for (voice = 0; voice < spuVmMaxVoice; voice++) {
        _svm_voice[voice].unk2 = 0x18;
        _svm_voice[voice].unk0 = 0xFF;
        _svm_voice[voice].unk1b = 0;
        _svm_voice[voice].unk04 = 0;
        _svm_voice[voice].unk6 = 0;
        _svm_voice[voice].unke = 0xFF;
        _svm_voice[voice].unk10 = 0;
        _svm_voice[voice].prog = 0;
        _svm_voice[voice].tone = 0xFF;

        pos = voice * 8;
        D_80032F10[pos + 0x6 / 2] = 0x200;
        D_80032F10[pos + 0x4 / 2] = 0x1000;
        D_80032F10[pos + 0x8 / 2] = 0x80ff;
        D_80032F10[pos + 0x0] = 0;
        D_80032F10[pos + 0x2 / 2] = 0;
        D_80032F10[pos + 0xa / 2] = 0x4000;

        _svm_cur.field_0x1a = voice;
        temp2 = get_field_0x1a();
        if (temp2 < 0x10) {
            bitsLower = 1 << temp2;
            bitsUpper = 0;
        } else {
            bitsLower = 0;
            bitsUpper = 1 << (temp2 - 0x10);
        }

        _svm_voice[temp2].unk1b = 0;
        _svm_voice[temp2].unk04 = 0;
        _svm_voice[temp2].unk0 = 0;

        _svm_okof1 |= bitsLower;
        _svm_okof2 |= bitsUpper;

        _svm_okon1 &= ~_svm_okof1;
        _svm_okon2 &= ~_svm_okof2;
    }
}
