/* Part of libsnd/vs_mono.c of the SDK reference: functions SsSetMono, SsSetStereo. Generated by sdkimport.py. */
// SPDX-License-Identifier: MIT
#include "libsnd_i.h"

void SsSetMono(void) { _svm_stereo_mono = 1; }

void SsSetStereo(void) { _svm_stereo_mono = 0; }
